### ISSUE TITLE
Ability to show the main window as a sidebar panel

### ISSUE THREAD

**Issue by tbertels** [Nitrama/HTTP-Header-Live#10]
It would be great to be able to show the HTTP-Header-Live Main as a sidebar panel.
It would also avoid the need for a toolbar button.

**Comment by Nitrama** [comment]
that is a very good idea.
I try to implement it.

**Comment by Nitrama** [comment]
die neue version wurde firefox übertragen

**Comment by tbertels** [comment]
Thanks, that was fast!

**Comment by bashM0nk3y** [comment]
How does one get the sidebar back after closing it?
Sorry if this is a newb question, but all I can manage at the moment is a separate window.

**Comment by tbertels** [comment]
You have to use the [sidebar button](https://support.mozilla.org/kb/firefox-sidebar-access-bookmarks-history-social).
