### ISSUE TITLE
Forms not displayed corectly on Ubuntu 16

### ISSUE THREAD

**Issue by caffedrine** [Nitrama/HTTP-Header-Live#11]
The buttons and windows simply are empty on Ubuntu 16 with Firefox Quantum installed!

I have to blindly click on that button in order to view content.

![peek 2018-02-20 12-59](https://user-images.githubusercontent.com/6045158/36420529-145e6242-163e-11e8-8890-e96cc8f08da2.gif)

The main window was also empty, I just clicked random to open replay window.

Later EDIT: The quick fix is to resize windows:
![peek 2018-02-20 12-59](https://user-images.githubusercontent.com/6045158/36420938-503fb382-163f-11e8-9aed-818c60ae2644.gif)

**Comment by Nitrama** [comment]
can you give me more information?
for example the Ubuntu version and the Firefox version?
and what else could help me.
But as it looks like this should be a Firefox / Ubuntu problem.

**Comment by caffedrine** [comment]
It'st Ubuntu 16.04.3 LTS with Firefox Quantum 58.0.2 (64-bit).

The addon was unusable until the trick with resizing and it took me some time to figure out. 

Have no clue what it could be! But people will know now if they have the same problem...

**Comment by Nitrama** [comment]
I could reproduce it.
it is a bug under Linux Firefox.

On Windows there is no such bug.
I have already posted it on bugzilla.mozilla.org.

Unfortunately, I can not do anything right now.
I'll let you know if something changes.

**Comment by amirsobhi** [comment]
@caffedrine , @Nitrama  - I have experienced the same nothing showing and your work around of resizing worked. My systems is RHEL 7.4 with Firefox 58.0.2 running Gnome 3 ( 3.22.3 )

**Comment by Nitrama** [comment]
the bug was confirmed yesterday
https://bugzilla.mozilla.org/show_bug.cgi?id=1440006
