### ISSUE TITLE
Issue when used in Ubuntu: Pop-up window is blank

### ISSUE THREAD

**Issue by a2t2** [Nitrama/HTTP-Header-Live#16]
Hello,

I tried to add your extension for Firefox version 60 on Ubuntu 16.04.
I open the extension in the sidebar. When I click one HTTP packet, a pop-up window comes up, but the window is blank. I have to maximize the window to see the HTTP details. Can you please fix the blank window so that it also shows the content without being maximized ? 

Thanks

**Comment by Nitrama** [comment]
Duplicate of https://github.com/Nitrama/HTTP-Header-Live/issues/11
