### ISSUE TITLE
Issue with Firefox Quantum

### ISSUE THREAD

**Issue by brunodallavalle** [Nitrama/HTTP-Header-Live#18]
Hello,
there is a bug with Firefox Quantum 60.0.2 (64bit)
Once installed, the plugin opens a side window (either left or right side).
If you close it, when you click on the tiny icon instead of reopen the side window it opens a new window which is completely blank

**Comment by Nitrama** [comment]
If you want to open the addon in the sidebar you have to do it that way.
https://support.mozilla.org/en-US/kb/firefox-sidebar-access-bookmarks-history-social

There is a bug under Ubuntu / Linux where the window remains empty, you have to resize it.
