### ISSUE TITLE
POST request payload is not always displayed.

### ISSUE THREAD

**Issue by weshatheleopard** [Nitrama/HTTP-Header-Live#19]
When the POST request has `Content-Type: application/x-www-form-urlencoded`, then the payload of the POST request is displayed just fine. However, when POST request has `Content-Type: application/json
`, nothing is displayed, and that's really sad because I'm trying to debug a JSON app. :cry: 

I think the problem is [right here](https://github.com/Nitrama/HTTP-Header-Live/blob/cb0fe88a4e40abd9a8d70e14a1558246dced320d/HTTPHeaderMain.js#L162): JSON in `requestBody` does not have any `formData`, and as such, this loop is not executing at all.

**Comment by Nitrama** [comment]
Do you have some pictures?
Or a link where I can understand.
Or perhaps a PHP file or something similar have?

**Comment by weshatheleopard** [comment]
When I use the following code, 
```
<form method="post" action="http://www.xxxxxx.com:8081">
  <input type="text" name="test_field" value="test_data">
  <input type="submit" value="Submit">
</form> 
```
I see the information being posted:
![Image](https://s8.postimg.cc/f7xpmwi5x/img1.png)

However, when I use XMLRPC
```
  var xhr = new XMLHttpRequest();
  xhr.open('get', 'http://www.xxxxxx.com:8081', true);
  xhr.send('test_data');
```
I do see the etirety of request, but I DO NOT see test_data.

From what I see, it happens because your plugin only looks at `requestBody.formData`, and if the data is not parseable, nothing happens. In that case, I would rather expect you to print the data as a string, without any attempts to modify it.

For example:
````
string2 = ''
for (var i in WEBREQUEST_DATA[ID].requestBody.formData) {
            string2 += i + "=" + WEBREQUEST_DATA[ID].requestBody.formData[i] + "&";
}
if (string2 != '') {
  // prettyfying worked, use the prettified string
  string = string + string2
} else { 
  // prettyfying did not work, use requestBody as is
  string = string +  WEBREQUEST_DATA[ID].requestBody
}
```

**Comment by Nitrama** [comment]
in the line "xhr.open ('get', 'http://www.xxxxxx.com:8081', true);" only a GET parameter is sent. And that's just shown in the URL.

**Comment by weshatheleopard** [comment]
I'm sorry, you are correct, I meant to write ""xhr.open ('post', 'http://www.xxxxxx.com:8081', true);".

(I spent like 2 hours trying to prepare a test case with screenshot and everything for you, but I wasn't able to because of XSS protection in modern browsers).

**Comment by Nitrama** [comment]
I found the bug and fixed it.
Thanks for your help.
The update will be available soon on Firefox and Chrome.
https://github.com/Nitrama/HTTP-Header-Live/commit/8e76a931f3cf503cada0fff4337dac306d19fe6b

**Comment by weshatheleopard** [comment]
:+1: :heart:

**Comment by weshatheleopard** [comment]
:heart: It's showing now (in the new version), thank you!!!
