### ISSUE TITLE
button "file save" does nothing

### ISSUE THREAD

**Issue by setop** [Nitrama/HTTP-Header-Live#20]
I recorded a web surfing session and was hopping to be able to save the record but button "file save" seems to do nothing. Do I miss something ?

**Comment by Nitrama** [comment]
Although I found a small bug, but the download works in itself. I would need more information from your system (OS, version, Chrome or Firefox and so on).

**Comment by Nitrama** [comment]
I have released a new version.
Can you tell me if it works now?

**Comment by setop** [comment]
Actually, session is save into a predefined file : ~/Downloaded/HTTPHeaderLive(n).txt, with n growing.
I was not aware of that when I opened this issue.

**Comment by James-Oswald** [comment]
Seems so obvious now that I've read this, but I was seriously struggling finding where it saved the files to. Thanks for opening the issue.
