### ISSUE TITLE
Github tab opens every time I launch my browser

### ISSUE THREAD

**Issue by lgherb** [Nitrama/HTTP-Header-Live#21]
I'd like to be able to use the 'HTTP-Header-Live' plugin for Firefox without having a tab to the "https://github.com/Nitrama/HTTP-Header-Live" page open every time I open my browser.

How do I make this stop?

This is like being spammed every time I open my browser. There does not appear to be a way to change this behavior through Firefox's settings.

Thanks.

**Comment by Nitrama** [comment]
Ohh, I'm really sorry.
Actually it should open only if the addon has an update.
I will provide a new version immediately. Tomorrow the problem is solved. :-)
