### ISSUE TITLE
Clicking the window anywhere opens a new window

### ISSUE THREAD

**Issue by jim-moe** [Nitrama/HTTP-Header-Live#22]
Firefox 60.1.0
HTTP Header Live 0.6.4

When a header display window is open and I click anywhere within the window, a new header display window is opened.

Also, when the header window is first opened, it does not display anything at all until I resize it, not even the control bar at the bottom.

**Comment by Nitrama** [comment]
I suspect you are using Linux. If it should be so unfortunately I can not change it because it is bug of Firefox. https://github.com/Nitrama/HTTP-Header-Live/issues/11
