### ISSUE TITLE
"Send" does not send

### ISSUE THREAD

**Issue by zweibieren** [Nitrama/HTTP-Header-Live#23]
I modified a request and clicked "Send"; nothing happened.

requested URL:   http://physpics.com/annals/2006/Korea/images/campusmapbig.ppt

**Comment by Nitrama** [comment]
I can understand the problem.
But unfortunately I have no solution for the problem so far.

**Comment by Nitrama** [comment]
The new Version is Working. 
But it will output a wrong file name. 
Unfortunately I can not fix that.
