### ISSUE TITLE
Cant POST requests

### ISSUE THREAD

**Issue by JonhSilver** [Nitrama/HTTP-Header-Live#29]
Always get error Error:Error: Illegal URL: blob:moz-extension://86702573-9422-4b8b-a61a-e78944f6c47e/d8f3df48-9663-4721-8f8e-16a8454d5b3a

**Comment by Nitrama** [comment]
The error occurs when the headers are not correct. I need more information.
At which URL this occurs. What exactly was done? Maybe you can make a video
where you can see everything?
