### ISSUE TITLE
Can we have PUT/DELETE/OPTIONS/TRACE options?

### ISSUE THREAD

**Issue by imv7** [Nitrama/HTTP-Header-Live#3]
How can we use PUT/DELETE/OPTIONS/TRACE ?

**Comment by Nitrama** [comment]
16ab6929f3b4a96affd67bde77a346982f92add7
the methods `CONNECT`, `TRACE`, or `TRACK` is a forbidden method.
https://fetch.spec.whatwg.org/#forbidden-method

Added HEAD, PUT, DELETE, OPTIONS, PATCH

the new Version is send to Firefox
