### ISSUE TITLE
Request Header on chrome

### ISSUE THREAD

**Issue by MEhdimmz** [Nitrama/HTTP-Header-Live#35]
hi 
after save http request on chrome if request is blocked http header not save in file but in firefox it's work i need it on chrome 

thanks

**Comment by Nitrama** [comment]
on Linux Mint and Chrome Version 80.0.3987.87 is it working.

can you give me more information?

**Comment by MEhdimmz** [comment]
Hi nitrama thanks for fast replay 
see picture 
i block second request form.php
and after save .txt file request header not show
but first request recaptcha have request header 
this problem not in firefox just in chrome

![nirtana](https://user-images.githubusercontent.com/61585227/75606469-53126c80-5b02-11ea-9118-86b93ef76514.png)

**Comment by Nitrama** [comment]
I'm very sorry but I don't understand.
Can you take another picture of Firefox the way it should really look?

**Comment by MEhdimmz** [comment]
Hi Again nitrama sorry for bad english see this attach
i blocked form.php in both browser now see result on firefox i have http reQuest Header but in chrome i dont have it it's right? i need this for chrome 


![nirtana](https://user-images.githubusercontent.com/61585227/75615233-7961f780-5b56-11ea-9b6a-2e7356fd1edf.png)

**Comment by Nitrama** [comment]
Now I get it.

The problem I have now is that in Chrome blocking URLs does not work for me.

That means I can't fix the problem.
I think it's a problem directly with Chrome.

**Comment by MEhdimmz** [comment]
use this add-ons on chrome to block url and test it again
[https://chrome.google.com/webstore/detail/http-request-blocker/eckpjmeijpoipmldfbckahppeonkoeko](url)
type full link in addon dont use regular exp

**Comment by Nitrama** [comment]
I can understand it now.
![FireFox_Chrome](https://user-images.githubusercontent.com/16880671/75701018-4a14cd00-5cb3-11ea-988d-d95a24b39637.png)


I looked up the code. And did a little trial and error.

I do not think I can influence the behavior of the addon.
I think that I can just in Chrome.
I'm sorry.

**Comment by MEhdimmz** [comment]
I cant understand can you fix this? Or is chrome problem?

**Comment by Nitrama** [comment]
I can't fix it.
It's a chrome problem.

**Comment by MEhdimmz** [comment]
Can you give me skype id ?
