### ISSUE TITLE
Headers nicht vollständig

### ISSUE THREAD

**Issue by Gidubi** [Nitrama/HTTP-Header-Live#4]
Hallo Martin,

vielen Dank für das tolle Plugin welches mit Firefox 57 schon recht gut funktioniert.
Leider scheint es als würde das Plugin nicht alle Headers aufzeichnen.

Beispiel:
Folgende URL:  "https://goo.gl/WMR9Ce" sollte: "http://track.webgains.com/click.html?wgcampaignid=1236655&wgprogramid=11079&wgtarget=www.gearbest.com/laptops/pp_786412.html" aufrufen.

Die track.webgains.com URL setzt folgende Parameter: "siteid=1236655&utm_source=webgains&utm_campaign=GearbestDE" welche in der folge URL vorhanden sind: "https://www.gearbest.com/?siteid=1236655&utm_source=webgains&utm_campaign=GearbestDE" jedoch nicht der eigentlich Aufruf in den Headers: http://track.webgains.com/click.html?wgcampaignid=1236655&wgprogramid=11079&wgtarget=www.gearbest.com/laptops/pp_786412.html".

Kurz: "http://track.webgains.com/click.html?wgcampaignid=1236655&wgprogramid=11079&wgtarget=www.gearbest.com/laptops/pp_786412.html" ist in den Headers nicht zu finden.

Getestet habe ich das unter Windows 10 - 1709, Firefox 57.0.3 (64-Bit).
Ein anderes Plugin: "https://addons.mozilla.org/de/firefox/addon/live-http-headers/" zeigt alles korrekt in Firefox 56 an.

Liegt es am Plugin oder blockiert hier Firefox 57 etwas?

Über dein Feedback freue ich mich sehr.

Beste Grüße
Gidubi

**Comment by Nitrama** [comment]
Hallo,

ich habe genau den gleichen Bug gestern Abend gefunden.

Ich habe auch schon herausgefunden wo der Bug liegt. 
Mir ist aber leider noch keine Idee gekommen wie ich ihn lösen kann.
Ich werde mich jetzt mal drin vertiefen und schauhen ob ich es heute gelöst bekomme.

Gruß Martin

**Comment by Nitrama** [comment]
https://github.com/Nitrama/HTTP-Header-Live/commit/fe77a9849a9f6acefc08b21ad29f5111b61fadaf

So es müsste gelöst sein.
Die neue version ist schon bei Firefox einreicht.
Dürfte nicht lange dauern zum freischalten.

Das Update kommt automatisch schneller gehts mit selber suchen lassen

**Comment by Gidubi** [comment]
Hallo Nitrama,

vielen Dank für dein Feedback.

Das schaut super aus und funktioniert - TOP!!!!
Du hast es aber auch richtig schnell gepatcht.

Vielen lieben Dank und ein gesundes neues Jahr.

Beste Grüße
Gidubi

**Comment by Gidubi** [comment]
Hallo Nitrama,

wir würden die gerne wenn du möchtest ein kleines Dankeschön per Paket zukommen lassen wenn das möglich ist?

Beste Grüße
Gidubi

**Comment by Nitrama** [comment]
Danke :-)

bitte verstehe das ich meine Adresse nicht einfach so jemmand im Internet geben kann. Auch wenn das nicht das Problem sein dürfte die rauszufinden.
Mir würde schon eine Bewertung auf https://addons.mozilla.org/de/android/addon/http-header-live/ reichen :-).
und so aus reiner neugier wer ist "wir"?

**Comment by Gidubi** [comment]
Hallo Nitrama,

vielen Dank für dein Feedback.

Wir sind Webgains: "http://www.webgains.com/public/de/" und wollten dich quasi für deine tolle Arbeit belohnen. Gibt es eine Möglichkeit sich per PM auszutauschen, dann könnten wir das anderweitig abwickeln?

Beste Grüße
Gidubi

**Comment by Nitrama** [comment]
Wenn du unbedingt möchtest :-) . Meine Email ist martinantrag@gmail.com
