### ISSUE TITLE
New Feature - Include URLs

### ISSUE THREAD

**Issue by Gidubi** [Nitrama/HTTP-Header-Live#5]
Hallo Nitrama,

ich hätte eventuell noch ein Vorschlag für eine Erweiterung der Plugins.
Es wäre auch nicht schlecht wenn man in den Einstellungen bestimmte URLs definieren könnte welche angezeigt werden sollen und der Rest nicht.

Beispielweise könnte man sagen zeige mir nur alles mit: "http://google.de"

Beste Grüße
Gidubi

**Comment by Nitrama** [comment]
Es gibt in den Optionen die möglichkeit das man bestimmte seiten ausschließen kann.
Ich denke damit bekommt man das auch ganz gut hin. 
In den Optionen kann man auch Dateiendungen ausschließen.

**Comment by Gidubi** [comment]
Hallo Nitrama,

vielen Dank für dein Feedback.

Beispielsweise suchen wir ob "track.webgains..." auf bestimmten Seiten vorkommt.
Hier wissen wir nicht welche URLs noch aufgerufen werden um diese Blacklisten zu können.
Klar kann man mit STRG + F nach sein Eintrag suchen, war nur so eine Idee falls man sich nur für bestimmte Domains interessiert.

Beste Grüße

**Comment by Nitrama** [comment]
Okay ich habe da mal was reingebastelt.

https://github.com/Nitrama/HTTP-Header-Live/commit/65757cb6597e8b5975a4035d51eebb49038fec23

das was in der neuen Option eingetragen ist muss in der URL vorkommen.
Ich hoffe das ist die richtige Option :-)

**Comment by Gidubi** [comment]
Du bist ein wahrer Meister.

Habe gerade die neue Funktion getestet und diese funktioniert wunderbar, Danke.
Nitrama Software = Meisterschmiede ;)
