### ISSUE TITLE
Feature - Ignore filters

### ISSUE THREAD

**Issue by Gidubi** [Nitrama/HTTP-Header-Live#6]
Hallo Nitrama,

ich hätte noch eine weitere Idee welches auf das bereits gelöste Ticket: "https://github.com/Nitrama/HTTP-Header-Live/issues/" aufbaut.

Wenn man eine Whitelist URL hinzufügt bekommt man auch nur diese ausgespielt, sprich nur die Daten die interessant sind. Nun kommt es doch selten vor das man wissen möchte was sonst noch ausgelöst wurde. Hier muss man dann alle Whitelist URLs entfernen und die Seite neu laden und anschließend alle Whitelist URLs manuell eintragen.

Ein Button "Ignore all Filters" oder "Show All" wäre hier perfekt.
Somit könnte jeder Filter setzen aber sich bei bedarf alles anzeigen lassen. ;)

**Comment by Nitrama** [comment]
Da ich jetzt leider kein Urlaub habe wird nicht so schnell gehen wie die letzten male :-)

Aber die Idee finde ich sehr gut :-)

**Comment by Nitrama** [comment]
#So,
Update kommt jetzt 
https://github.com/Nitrama/HTTP-Header-Live/commit/9ee6860bf899210c0c9ce94c1e1635ed434fffac
