### ISSUE TITLE
Datei ausgabe nicht in der selben reihenfolge wie ausgabe

### ISSUE THREAD

**Issue by Nitrama** [Nitrama/HTTP-Header-Live#7]
mir wurde gerade zugetragen das in der Datei ausgabe nicht die Selbe reihen folge ist wie im Fenster.

Ich weiß auch schon an was es liegt. Da ich aber gerade keine Ahnung habe werde ich es erstmal nach hinten verschieben. Sobalb mir was einfällt werde ich es korrigieren.

Gruß Nitrama

**Comment by Zeokat** [comment]
Maybe if you write in english people can help.

**Comment by Nitrama** [comment]
my English is very bad. sorry.

Google Translate:
the file output does not have the same order as in the window

**Comment by 0joshuaolson1** [comment]
The first line of the comment is basically the issue name (the Google-translated "file output" thing). The rest says

I already know what it is. But since I have no idea, I'll postpone it first. As soon as I remember what I will correct it.

Greeting Nitrama

**Comment by Nitrama** [comment]
Ich habe es jetzt nochmal nachgeschaut. Mir fällt einfach kein grund ein wieso es so sein sollte.
Wenn jemmand mal ein beispiel hat bitte mir mal zukommen lassen.

Google Translate:
I looked it up again. I can not think of any reason why it should be so.
If somebody has an example please let me know.
