### ISSUE TITLE
No full GET header shown

### ISSUE THREAD

**Issue by ghost** [Nitrama/HTTP-Header-Live#8]
The GET header isn't fully shown:
```
https://github.com/preview?markdown_unsupported=false&repository=100526488&subject=0&subject_type=Issue
Host: github.com
...
```
It should start like this:
`GET https://github.com/preview?markdown_unsupported=false&repository=100526488&subject=0&subject_type=Issue HTTP/1.1` (or something like that)

Sometimes it's important to see whether GET or POST was used or which HTTP version, therefore it is pretty important this isn't shortened.

**Comment by Zeokat** [comment]
+1 for this request.

**Comment by Nitrama** [comment]
is added https://github.com/Nitrama/HTTP-Header-Live/commit/47a29396a20fa022060df2a5327f57148bb33a58

New Version is Online
